### Prepare Data 📝

##### Merge Dataset 🔂

In [29]:
import pandas as pd

Dataframe

In [30]:
# Carmell Directory
links_df = pd.read_csv(r"C:\coding\Data Mining\Movie-Recommendation-System\Data\ml-latest-small\links.csv")
movies_df = pd.read_csv(r"C:\coding\Data Mining\Movie-Recommendation-System\Data\ml-latest-small\movies.csv")
ratings_df = pd.read_csv(r"C:\coding\Data Mining\Movie-Recommendation-System\Data\ml-latest-small\ratings.csv").sort_values(by=["userId"])
tags_df = pd.read_csv(r"C:\coding\Data Mining\Movie-Recommendation-System\Data\ml-latest-small\tags.csv").sort_values(by=["userId"])

# Wormy Directory
# links_df = pd.read_csv(r"D:\Python Course\Movie Recommendation System\Data\ml-latest-small\links.csv")
# movies_df = pd.read_csv(r"D:\Python Course\Movie Recommendation System\Data\ml-latest-small\movies.csv")
# ratings_df = pd.read_csv(r"D:\Python Course\Movie Recommendation System\Data\ml-latest-small\ratings.csv").sort_values(by=["userId"])
# tags_df = pd.read_csv(r"D:\Python Course\Movie Recommendation System\Data\ml-latest-small\tags.csv").sort_values(by=["userId"])

In [31]:
links_df.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [32]:
movies_df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [33]:
ratings_df.head()

     userId  movieId  rating  timestamp
175       1     2648     4.0  964983414
174       1     2644     4.0  964983393
173       1     2641     5.0  964982620
172       1     2640     4.0  964982377
171       1     2628     4.0  964980523

In [34]:
tags_df.head()

   userId  movieId              tag   timestamp
2       2    60756     will ferrell  1445714992
0       2    60756            funny  1445714994
1       2    60756  Highly quotable  1445714996
8       2   106782  Martin Scorsese  1445715056
6       2   106782            drugs  1445715054

Merge Dataframes

In [35]:
# Merge Data
merge1_df = ratings_df.merge(
    movies_df,
    on="movieId",
    how="left"
).merge(
    tags_df[["movieId", "tag"]],
    on="movieId",
    how="left"
).merge(
    links_df,
    on="movieId",
    how="left"
).dropna(axis=0)

merge1_df.head()

,userId,movieId,rating,timestamp,title,genres,tag,imdbId,tmdbId
0,1,2648,4.0,964983414,Frankenstein (1931),Drama|Horror|Sci-Fi,In Netflix queue,21884,3035.0
2,1,2641,5.0,964982620,Superman II (1980),Action|Sci-Fi,superhero,81573,8536.0
3,1,2640,4.0,964982377,Superman (1978),Action|Adventure|Sci-Fi,superhero,78346,1924.0
4,1,2628,4.0,964980523,Star Wars: Episode I - The Phantom Menace (1999),Action|Adventure|Sci-Fi,the Force,120915,1893.0
5,1,2628,4.0,964980523,Star Wars: Episode I - The Phantom Menace (1999),Action|Adventure|Sci-Fi,prequel,120915,1893.0

In [36]:
movieLens_df = merge1_df[["userId", "movieId", "title", "genres",
                          "tag", "rating", "imdbId", "tmdbId"]]
movieLens_df.head()

,userId,movieId,title,genres,tag,rating,imdbId,tmdbId
0,1,2648,Frankenstein (1931),Drama|Horror|Sci-Fi,In Netflix queue,4.0,21884,3035.0
2,1,2641,Superman II (1980),Action|Sci-Fi,superhero,5.0,81573,8536.0
3,1,2640,Superman (1978),Action|Adventure|Sci-Fi,superhero,4.0,78346,1924.0
4,1,2628,Star Wars: Episode I - The Phantom Menace (1999),Action|Adventure|Sci-Fi,the Force,4.0,120915,1893.0
5,1,2628,Star Wars: Episode I - The Phantom Menace (1999),Action|Adventure|Sci-Fi,prequel,4.0,120915,1893.0

### EDA MovieLens Dataframe

##### Understanding Dataframes Structure

In [37]:
movieLens_df.dtypes

userId       int64
movieId      int64
title       object
genres      object
tag         object
rating     float64
imdbId       int64
tmdbId     float64
dtype: object

In [38]:
movieLens_df[movieLens_df == movieLens_df.duplicated]

        userId  movieId title genres  tag  rating  imdbId  tmdbId
0          NaN      NaN   NaN    NaN  NaN     NaN     NaN     NaN
2          NaN      NaN   NaN    NaN  NaN     NaN     NaN     NaN
3          NaN      NaN   NaN    NaN  NaN     NaN     NaN     NaN
4          NaN      NaN   NaN    NaN  NaN     NaN     NaN     NaN
5          NaN      NaN   NaN    NaN  NaN     NaN     NaN     NaN
...        ...      ...   ...    ...  ...     ...     ...     ...
285753     NaN      NaN   NaN    NaN  NaN     NaN     NaN     NaN
285754     NaN      NaN   NaN    NaN  NaN     NaN     NaN     NaN
285755     NaN      NaN   NaN    NaN  NaN     NaN     NaN     NaN
285756     NaN      NaN   NaN    NaN  NaN     NaN     NaN     NaN
285757     NaN      NaN   NaN    NaN  NaN     NaN     NaN     NaN

[233213 rows x 8 columns]

In [50]:
movieLens_df["genres"] = movieLens_df["genres"].str.strip().str.replace("|", ",", regex=False)
movieLens_df

C:\Users\User\AppData\Local\Temp\ipykernel_22112\2887509947.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movieLens_df["genres"] = movieLens_df["genres"].str.strip().str.replace("|", ",", regex=False)

,userId,movieId,title,genres,tag,rating,imdbId,tmdbId
0,1,2648,Frankenstein (1931),"Drama,Horror,Sci-Fi",In Netflix queue,4.0,21884,3035.0
2,1,2641,Superman II (1980),"Action,Sci-Fi",superhero,5.0,81573,8536.0
3,1,2640,Superman (1978),"Action,Adventure,Sci-Fi",superhero,4.0,78346,1924.0
4,1,2628,Star Wars: Episode I - The Phantom Menace (1999),"Action,Adventure,Sci-Fi",the Force,4.0,120915,1893.0
5,1,2628,Star Wars: Episode I - The Phantom Menace (1999),"Action,Adventure,Sci-Fi",prequel,4.0,120915,1893.0
...,...,...,...,...,...,...,...,...
285753,610,158872,Sausage Party (2016),"Animation,Comedy",Vulgar,3.5,1700841,223702.0
285754,610,158872,Sausage Party (2016),"Animation,Comedy",satire,3.5,1700841,223702.0
285755,610,158872,Sausage Party (2016),"Animation,Comedy",sarcasm,3.5,1700841,223702.0
285756,610,158872,Sausage Party (2016),"Animation,Comedy",mindfuck,3.5,1700841,223702.0
285757,610,158872,Sausage Party (2016),"Animation,Comedy",Crude humor,3.5,1700841,223702.0