### Prepare Data

#### Combined DataSet

In [1]:
import pandas as pd

In [2]:
# Dataframes
links_df = pd.read_csv(r"C:\coding\Data Mining\Movie-Recommendation-System\Data\ml-latest-small\links.csv")
movies_df = pd.read_csv(r"C:\coding\Data Mining\Movie-Recommendation-System\Data\ml-latest-small\movies.csv")
ratings_df = pd.read_csv(r"C:\coding\Data Mining\Movie-Recommendation-System\Data\ml-latest-small\ratings.csv").sort_values(by=["userId"])
tags_df = pd.read_csv(r"C:\coding\Data Mining\Movie-Recommendation-System\Data\ml-latest-small\tags.csv").sort_values(by=["userId"])

In [3]:
links_df.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [4]:
movies_df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [5]:
ratings_df.head()

     userId  movieId  rating  timestamp
175       1     2648     4.0  964983414
174       1     2644     4.0  964983393
173       1     2641     5.0  964982620
172       1     2640     4.0  964982377
171       1     2628     4.0  964980523

In [6]:
tags_df.head()

   userId  movieId              tag   timestamp
2       2    60756     will ferrell  1445714992
0       2    60756            funny  1445714994
1       2    60756  Highly quotable  1445714996
8       2   106782  Martin Scorsese  1445715056
6       2   106782            drugs  1445715054

In [7]:
# Combinedata
# Movies_df = pd.concat([movies_df, tags_df])
get_Movie_Name = movies_df.loc[ratings_df["movieId"].isin(movies_df["movieId"]), "title"]

In [8]:
get_Movie_Name

0                                Toy Story (1995)
1                                  Jumanji (1995)
2                         Grumpier Old Men (1995)
3                        Waiting to Exhale (1995)
4              Father of the Bride Part II (1995)
                          ...
9737    Black Butler: Book of the Atlantic (2017)
9738                 No Game No Life: Zero (2017)
9739                                 Flint (2017)
9740          Bungo Stray Dogs: Dead Apple (2018)
9741          Andrew Dice Clay: Dice Rules (1991)
Name: title, Length: 9742, dtype: object