### Prepare Data 📝

##### Merge Dataset 🔂

In [47]:
import pandas as pd

Dataframe

In [48]:
# Carmell Directory
# links_df = pd.read_csv(r"C:\coding\Data Mining\Movie-Recommendation-System\Data\ml-latest-small\links.csv")
# movies_df = pd.read_csv(r"C:\coding\Data Mining\Movie-Recommendation-System\Data\ml-latest-small\movies.csv")
# ratings_df = pd.read_csv(r"C:\coding\Data Mining\Movie-Recommendation-System\Data\ml-latest-small\ratings.csv").sort_values(by=["userId"])
# tags_df = pd.read_csv(r"C:\coding\Data Mining\Movie-Recommendation-System\Data\ml-latest-small\tags.csv").sort_values(by=["userId"])

# Wormy Directory
links_df = pd.read_csv(r"D:\Python Course\Movie Recommendation System\Data\ml-latest-small\links.csv")
movies_df = pd.read_csv(r"D:\Python Course\Movie Recommendation System\Data\ml-latest-small\movies.csv")
ratings_df = pd.read_csv(r"D:\Python Course\Movie Recommendation System\Data\ml-latest-small\ratings.csv").sort_values(by=["userId"])
tags_df = pd.read_csv(r"D:\Python Course\Movie Recommendation System\Data\ml-latest-small\tags.csv").sort_values(by=["userId"])

In [49]:
links_df.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [50]:
movies_df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [51]:
ratings_df.head()

     userId  movieId  rating  timestamp
180       1     2716     5.0  964983414
181       1     2761     5.0  964982703
182       1     2797     4.0  964981710
183       1     2826     4.0  964980523
184       1     2858     5.0  964980868

In [52]:
tags_df.head()

   userId  movieId              tag   timestamp
0       2    60756            funny  1445714994
1       2    60756  Highly quotable  1445714996
2       2    60756     will ferrell  1445714992
8       2   106782  Martin Scorsese  1445715056
6       2   106782            drugs  1445715054

Merge Dataframes

In [53]:
# Merge Data
merge1_df = ratings_df.merge(
    movies_df,
    on="movieId",
    how="left"
).merge(
    tags_df[["movieId", "tag"]],
    on="movieId",
    how="left"
).merge(
    links_df,
    on="movieId",
    how="left"
).dropna(axis=0)

merge1_df.head()

,userId,movieId,rating,timestamp,title,genres,tag,imdbId,tmdbId
0,1,2716,5.0,964983414,Ghostbusters (a.k.a. Ghost Busters) (1984),Action|Comedy|Sci-Fi,ghosts,87332,620.0
1,1,2761,5.0,964982703,"Iron Giant, The (1999)",Adventure|Animation|Children|Drama|Sci-Fi,robots,129167,10386.0
2,1,2761,5.0,964982703,"Iron Giant, The (1999)",Adventure|Animation|Children|Drama|Sci-Fi,animation,129167,10386.0
3,1,2797,4.0,964981710,Big (1988),Comedy|Drama|Fantasy|Romance,children,94737,2280.0
6,1,2872,5.0,964981680,Excalibur (1981),Adventure|Fantasy,England,82348,11527.0

In [54]:
movieLens_df = merge1_df[["userId", "movieId", "title", "genres",
                          "tag", "rating", "imdbId", "tmdbId"]]
movieLens_df.head()

,userId,movieId,title,genres,tag,rating,imdbId,tmdbId
0,1,2716,Ghostbusters (a.k.a. Ghost Busters) (1984),Action|Comedy|Sci-Fi,ghosts,5.0,87332,620.0
1,1,2761,"Iron Giant, The (1999)",Adventure|Animation|Children|Drama|Sci-Fi,robots,5.0,129167,10386.0
2,1,2761,"Iron Giant, The (1999)",Adventure|Animation|Children|Drama|Sci-Fi,animation,5.0,129167,10386.0
3,1,2797,Big (1988),Comedy|Drama|Fantasy|Romance,children,4.0,94737,2280.0
6,1,2872,Excalibur (1981),Adventure|Fantasy,England,5.0,82348,11527.0